spring.application.name=mastersys
# Datasource configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

